### ISSUE TITLE
Compile failed on ESP8266 3.x board toolchain

### ISSUE THREAD

**Issue by lededev** [hunamizawa/ESPPerfectTime#4]
This library work well on ESP8266 v2.7.4 board toolchain or early(Arduino->Tools->Board->Board Manager->input keyword `8266` search board).
But after upgrade to v3.0.0 .. v3.0.2, compile failed with message
```
Alternatives for sntp-lwip2.h: []
ResolveLibrary(sntp-lwip2.h)
D:\Arduino\libraries\ESPPerfectTime\src\ESPPerfectTime.cpp:7:10: fatal error: sntp-lwip2.h: No such file or directory
  -> candidates: []
    7 | #include <sntp-lwip2.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

```
